### PR TITLE
Fix/naming convention

### PR DESCRIPTION
**Pull request by gareth-cross**
- Rename frame convention menu for clarity.
- Fix issue introduced in #10 where the map could shift when transformAerialMap was triggered. The timestamp of the reference lat/lon is used in combination with the frame manager to make sure the correct TF is used, even if other options change.
- Introduce constants for max blocks, max zoom, and raise max blocks to 8.
- Rename misc variables and add comments.

Frame conventions:
libGeogrphic (actually also ROS, according to [REP103](www.ros.org/reps/rep-0103.html)) maps to 'XYZ -> ENU'
ROS (which was incorrectly named, oops) maps to 'XYZ -> NWU'

### CODE REVIEW

**Comment by chataign** [comment]
I’m reviewing this but having problems with the change to the timestamp used for the transform lookup. I'm now seeing map jumps which I wasn't seeing before. What was the issue with using ros::Time(0) ie. the most recent transform?

**Comment by gareth-cross** [comment]
Strange. What TF are you publishing? In the tests I ran the TF was the world_T_body transform of the robot (as given by GPS, converted to cartesian with libGeographic). If I use ros::Time(), issues occur when `transformAerialMap()` is called in `updateFrame()` or `updateFrameConvention()` or `fixedFrameChanged()`. In these cases, the latest TF does not correspond to the one used to set the map origin (which occurs in `navFixCallback`). The map looks shifted as compared to the odometry being rendered by rviz.

**Comment by chataign** [comment]
Sorry for the delay, I'm pretty swamped this week and haven't had time to look into it. 
Will have a look over the weekend!

**Comment by chataign** [comment]
turns out the issue I was having was in fact due to a bug in our data collection scripts! (gps timestamps were not synchronized properly). Apologies for the delay, I tested your changes and all is working now. Thanks

**Comment by gareth-cross** [comment]
Cool, thanks for merging.

**Pull request merged**
